#############################################################################
# Makefile for building: evolver_editor
# Generated by qmake (2.01a) (Qt 4.4.0) on: Wed Jan 21 09:35:55 2009
# Project:  evolver_editor.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile evolver_editor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -Imoc -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/common.cpp \
		src/sliderspinbox.cpp \
		src/main.cpp \
		src/oscmodel.cpp \
		src/oscview.cpp \
		src/modulators.cpp \
		src/modulation_destinations.cpp \
		src/lfo.cpp \
		src/applicationmodel.cpp \
		src/applicationview.cpp moc/moc_sliderspinbox.cpp \
		moc/moc_oscmodel.cpp \
		moc/moc_oscview.cpp \
		moc/moc_modulators.cpp \
		moc/moc_lfo.cpp \
		moc/moc_applicationmodel.cpp \
		moc/moc_applicationview.cpp
OBJECTS       = obj/common.o \
		obj/sliderspinbox.o \
		obj/main.o \
		obj/oscmodel.o \
		obj/oscview.o \
		obj/modulators.o \
		obj/modulation_destinations.o \
		obj/lfo.o \
		obj/applicationmodel.o \
		obj/applicationview.o \
		obj/moc_sliderspinbox.o \
		obj/moc_oscmodel.o \
		obj/moc_oscview.o \
		obj/moc_modulators.o \
		obj/moc_lfo.o \
		obj/moc_applicationmodel.o \
		obj/moc_applicationview.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		evolver_editor.pro
QMAKE_TARGET  = evolver_editor
DESTDIR       = 
TARGET        = evolver_editor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: evolver_editor.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile evolver_editor.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile evolver_editor.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/evolver_editor1.0.0 || $(MKDIR) obj/evolver_editor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/evolver_editor1.0.0/ && $(COPY_FILE) --parents include/common.hpp include/sliderspinbox.hpp include/oscmodel.hpp include/oscview.hpp include/modulators.hpp include/modulation_destinations.hpp include/modulation_sources.hpp include/lfo.hpp include/applicationmodel.hpp include/applicationview.hpp obj/evolver_editor1.0.0/ && $(COPY_FILE) --parents src/common.cpp src/sliderspinbox.cpp src/main.cpp src/oscmodel.cpp src/oscview.cpp src/modulators.cpp src/modulation_destinations.cpp src/lfo.cpp src/applicationmodel.cpp src/applicationview.cpp obj/evolver_editor1.0.0/ && (cd `dirname obj/evolver_editor1.0.0` && $(TAR) evolver_editor1.0.0.tar evolver_editor1.0.0 && $(COMPRESS) evolver_editor1.0.0.tar) && $(MOVE) `dirname obj/evolver_editor1.0.0`/evolver_editor1.0.0.tar.gz . && $(DEL_FILE) -r obj/evolver_editor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_sliderspinbox.cpp moc/moc_oscmodel.cpp moc/moc_oscview.cpp moc/moc_modulators.cpp moc/moc_lfo.cpp moc/moc_applicationmodel.cpp moc/moc_applicationview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_sliderspinbox.cpp moc/moc_oscmodel.cpp moc/moc_oscview.cpp moc/moc_modulators.cpp moc/moc_lfo.cpp moc/moc_applicationmodel.cpp moc/moc_applicationview.cpp
moc/moc_sliderspinbox.cpp: include/sliderspinbox.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/sliderspinbox.hpp -o moc/moc_sliderspinbox.cpp

moc/moc_oscmodel.cpp: include/oscmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/oscmodel.hpp -o moc/moc_oscmodel.cpp

moc/moc_oscview.cpp: include/oscview.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/oscview.hpp -o moc/moc_oscview.cpp

moc/moc_modulators.cpp: include/modulators.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/modulators.hpp -o moc/moc_modulators.cpp

moc/moc_lfo.cpp: include/lfo.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/lfo.hpp -o moc/moc_lfo.cpp

moc/moc_applicationmodel.cpp: include/applicationmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/applicationmodel.hpp -o moc/moc_applicationmodel.cpp

moc/moc_applicationview.cpp: include/applicationview.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/applicationview.hpp -o moc/moc_applicationview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/common.o: src/common.cpp include/common.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/common.o src/common.cpp

obj/sliderspinbox.o: src/sliderspinbox.cpp include/sliderspinbox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sliderspinbox.o src/sliderspinbox.cpp

obj/main.o: src/main.cpp include/oscmodel.hpp \
		include/oscview.hpp \
		include/lfo.hpp \
		include/modulation_destinations.hpp \
		include/applicationmodel.hpp \
		include/applicationview.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/oscmodel.o: src/oscmodel.cpp include/oscmodel.hpp \
		include/common.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/oscmodel.o src/oscmodel.cpp

obj/oscview.o: src/oscview.cpp include/oscview.hpp \
		include/oscmodel.hpp \
		include/sliderspinbox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/oscview.o src/oscview.cpp

obj/modulators.o: src/modulators.cpp include/modulators.hpp \
		include/modulation_destinations.hpp \
		include/modulation_sources.hpp \
		include/sliderspinbox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/modulators.o src/modulators.cpp

obj/modulation_destinations.o: src/modulation_destinations.cpp include/modulation_destinations.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/modulation_destinations.o src/modulation_destinations.cpp

obj/lfo.o: src/lfo.cpp include/lfo.hpp \
		include/common.hpp \
		include/modulation_destinations.hpp \
		include/modulators.hpp \
		include/sliderspinbox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/lfo.o src/lfo.cpp

obj/applicationmodel.o: src/applicationmodel.cpp include/applicationmodel.hpp \
		include/lfo.hpp \
		include/oscmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/applicationmodel.o src/applicationmodel.cpp

obj/applicationview.o: src/applicationview.cpp include/applicationview.hpp \
		include/oscview.hpp \
		include/lfo.hpp \
		include/modulators.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/applicationview.o src/applicationview.cpp

obj/moc_sliderspinbox.o: moc/moc_sliderspinbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_sliderspinbox.o moc/moc_sliderspinbox.cpp

obj/moc_oscmodel.o: moc/moc_oscmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_oscmodel.o moc/moc_oscmodel.cpp

obj/moc_oscview.o: moc/moc_oscview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_oscview.o moc/moc_oscview.cpp

obj/moc_modulators.o: moc/moc_modulators.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_modulators.o moc/moc_modulators.cpp

obj/moc_lfo.o: moc/moc_lfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_lfo.o moc/moc_lfo.cpp

obj/moc_applicationmodel.o: moc/moc_applicationmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_applicationmodel.o moc/moc_applicationmodel.cpp

obj/moc_applicationview.o: moc/moc_applicationview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_applicationview.o moc/moc_applicationview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

